//
//  ZQTVMStatistics.cpp
//  ZqtOOMDetector
//
//  Created by 张千通 on 2025/5/12.
//

#include "ZQTVMStatistics.hpp"
#include <string.h>
#include <map>
#include <set>
#include <mach/vm_statistics.h>

using namespace std;

static std::map<int, string> vm_region_names = {
    {VM_MEMORY_MALLOC, "VM_MEMORY_MALLOC"},
    {VM_MEMORY_MALLOC_SMALL, "VM_MEMORY_MALLOC"},
    {VM_MEMORY_MALLOC_LARGE, "VM_MEMORY_MALLOC"},
    {VM_MEMORY_MALLOC_HUGE, "VM_MEMORY_MALLOC"},
    {VM_MEMORY_SBRK, "VM_MEMORY_SBRK"},
    {VM_MEMORY_REALLOC, "VM_MEMORY_MALLOC"},
    {VM_MEMORY_MALLOC_TINY, "VM_MEMORY_MALLOC"},
    {VM_MEMORY_MALLOC_LARGE_REUSABLE, "VM_MEMORY_MALLOC"},
    {VM_MEMORY_MALLOC_LARGE_REUSED, "VM_MEMORY_MALLOC"},
    {VM_MEMORY_ANALYSIS_TOOL, "VM_MEMORY_ANALYSIS_TOOL"},
    {VM_MEMORY_MALLOC_NANO, "VM_MEMORY_MALLOC"},
    {VM_MEMORY_MALLOC_MEDIUM, "VM_MEMORY_MALLOC"},
    {VM_MEMORY_MALLOC_PROB_GUARD, "VM_MEMORY_MALLOC"},
    
    {VM_MEMORY_MACH_MSG, "VM_MEMORY_MACH_MSG"},
    {VM_MEMORY_IOKIT, "VM_MEMORY_IOKIT"},
    {VM_MEMORY_STACK, "VM_MEMORY_STACK"},
    {VM_MEMORY_GUARD, "VM_MEMORY_GUARD"},
    {VM_MEMORY_SHARED_PMAP, "VM_MEMORY_SHARED_PMAP"},
    {VM_MEMORY_DYLIB, "VM_MEMORY_DYLIB"},
    {VM_MEMORY_OBJC_DISPATCHERS, "VM_MEMORY_OBJC_DISPATCHERS"},
    {VM_MEMORY_UNSHARED_PMAP, "VM_MEMORY_UNSHARED_PMAP"},
    
    {VM_MEMORY_APPKIT, "VM_MEMORY_APPKIT"},
    {VM_MEMORY_FOUNDATION, "VM_MEMORY_FOUNDATION"},
    {VM_MEMORY_COREGRAPHICS, "VM_MEMORY_COREGRAPHICS"},
    {VM_MEMORY_CORESERVICES, "VM_MEMORY_CORESERVICES"},
    {VM_MEMORY_JAVA, "VM_MEMORY_JAVA"},
    {VM_MEMORY_COREDATA, "VM_MEMORY_COREDATA"},
    {VM_MEMORY_COREDATA_OBJECTIDS, "VM_MEMORY_COREDATA_OBJECTIDS"},
    {VM_MEMORY_ATS, "VM_MEMORY_ATS"},
    {VM_MEMORY_LAYERKIT, "VM_MEMORY_LAYERKIT"},
    {VM_MEMORY_CGIMAGE, "VM_MEMORY_CGIMAGE"},
    {VM_MEMORY_TCMALLOC, "VM_MEMORY_TCMALLOC"},
    
    {VM_MEMORY_COREGRAPHICS_DATA, "VM_MEMORY_COREGRAPHICS_DATA"},
    {VM_MEMORY_COREGRAPHICS_SHARED, "VM_MEMORY_COREGRAPHICS_SHARED"},
    {VM_MEMORY_COREGRAPHICS_FRAMEBUFFERS, "VM_MEMORY_COREGRAPHICS_FRAMEBUFFERS"},
    {VM_MEMORY_COREGRAPHICS_BACKINGSTORES, "VM_MEMORY_COREGRAPHICS_BACKINGSTORES"},
    {VM_MEMORY_COREGRAPHICS_XALLOC, "VM_MEMORY_COREGRAPHICS_XALLOC"},
    {VM_MEMORY_DYLD, "VM_MEMORY_DYLD"},
    {VM_MEMORY_DYLD_MALLOC, "VM_MEMORY_DYLD_MALLOC"},
    {VM_MEMORY_SQLITE, "VM_MEMORY_SQLITE"},
    {VM_MEMORY_JAVASCRIPT_CORE, "VM_MEMORY_JAVASCRIPT_CORE"},
    {VM_MEMORY_JAVASCRIPT_JIT_EXECUTABLE_ALLOCATOR, "VM_MEMORY_JAVASCRIPT_JIT_EXECUTABLE_ALLOCATOR"},
    {VM_MEMORY_JAVASCRIPT_JIT_REGISTER_FILE, "VM_MEMORY_JAVASCRIPT_JIT_REGISTER_FILE"},
    {VM_MEMORY_GLSL, "VM_MEMORY_GLSL"},
    {VM_MEMORY_OPENCL, "VM_MEMORY_OPENCL"},
    {VM_MEMORY_COREIMAGE, "VM_MEMORY_COREIMAGE"},
    {VM_MEMORY_WEBCORE_PURGEABLE_BUFFERS, "VM_MEMORY_WEBCORE_PURGEABLE_BUFFERS"},
    {VM_MEMORY_IMAGEIO, "VM_MEMORY_IMAGEIO"},
    {VM_MEMORY_COREPROFILE, "VM_MEMORY_COREPROFILE"},
    {VM_MEMORY_ASSETSD, "VM_MEMORY_ASSETSD"},
    {VM_MEMORY_OS_ALLOC_ONCE, "VM_MEMORY_OS_ALLOC_ONCE"},
    {VM_MEMORY_LIBDISPATCH, "VM_MEMORY_LIBDISPATCH"},
    {VM_MEMORY_ACCELERATE, "VM_MEMORY_ACCELERATE"},
    {VM_MEMORY_COREUI, "VM_MEMORY_COREUI"},
    {VM_MEMORY_COREUIFILE, "VM_MEMORY_COREUIFILE"},
    {VM_MEMORY_GENEALOGY, "VM_MEMORY_GENEALOGY"},
    {VM_MEMORY_RAWCAMERA, "VM_MEMORY_RAWCAMERA"},
    {VM_MEMORY_CORPSEINFO, "VM_MEMORY_CORPSEINFO"},
    {VM_MEMORY_ASL, "VM_MEMORY_ASL"},
    {VM_MEMORY_SWIFT_RUNTIME, "VM_MEMORY_SWIFT_RUNTIME"},
    {VM_MEMORY_SWIFT_METADATA, "VM_MEMORY_SWIFT_METADATA"},
    {VM_MEMORY_DHMM, "VM_MEMORY_DHMM"},
    {VM_MEMORY_SCENEKIT, "VM_MEMORY_SCENEKIT"},
    {VM_MEMORY_SKYWALK, "VM_MEMORY_SKYWALK"},
    {VM_MEMORY_IOSURFACE, "VM_MEMORY_IOSURFACE"},
    {VM_MEMORY_LIBNETWORK, "VM_MEMORY_LIBNETWORK"},
    {VM_MEMORY_AUDIO, "VM_MEMORY_AUDIO"},
    {VM_MEMORY_VIDEOBITSTREAM, "VM_MEMORY_VIDEOBITSTREAM"},
    {VM_MEMORY_CM_XPC, "VM_MEMORY_CM_XPC"},
    {VM_MEMORY_CM_RPC, "VM_MEMORY_CM_RPC"},
    {VM_MEMORY_CM_MEMORYPOOL, "VM_MEMORY_CM_MEMORYPOOL"},
    {VM_MEMORY_CM_READCACHE, "VM_MEMORY_CM_READCACHE"},
    {VM_MEMORY_CM_CRABS, "VM_MEMORY_CM_CRABS"},
    {VM_MEMORY_QUICKLOOK_THUMBNAILS, "VM_MEMORY_QUICKLOOK_THUMBNAILS"},
    {VM_MEMORY_ACCOUNTS, "VM_MEMORY_ACCOUNTS"},
    {VM_MEMORY_SANITIZER, "VM_MEMORY_SANITIZER"},
    {VM_MEMORY_IOACCELERATOR, "VM_MEMORY_IOACCELERATOR"},
    {VM_MEMORY_CM_REGWARP, "VM_MEMORY_CM_REGWARP"},
    {VM_MEMORY_EAR_DECODER, "VM_MEMORY_EAR_DECODER"},
    {VM_MEMORY_COREUI_CACHED_IMAGE_DATA, "VM_MEMORY_COREUI_CACHED_IMAGE_DATA"},
    {VM_MEMORY_COLORSYNC, "VM_MEMORY_COLORSYNC"},
    {105, "VM_MEMORY_BTINFO"},
    
    {VM_MEMORY_ROSETTA, "VM_MEMORY_ROSETTA"},
    {VM_MEMORY_ROSETTA_THREAD_CONTEXT, "VM_MEMORY_ROSETTA_THREAD_CONTEXT"},
    {VM_MEMORY_ROSETTA_INDIRECT_BRANCH_MAP, "VM_MEMORY_ROSETTA_INDIRECT_BRANCH_MAP"},
    {VM_MEMORY_ROSETTA_RETURN_STACK, "VM_MEMORY_ROSETTA_RETURN_STACK"},
    {VM_MEMORY_ROSETTA_EXECUTABLE_HEAP, "VM_MEMORY_ROSETTA_EXECUTABLE_HEAP"},
    {VM_MEMORY_ROSETTA_USER_LDT, "VM_MEMORY_ROSETTA_USER_LDT"},
    {VM_MEMORY_ROSETTA_ARENA, "VM_MEMORY_ROSETTA_ARENA"},
    {VM_MEMORY_ROSETTA_10, "VM_MEMORY_ROSETTA_10"},
    {VM_MEMORY_APPLICATION_SPECIFIC_1, "VM_MEMORY_APPLICATION_SPECIFIC_1"},
    {VM_MEMORY_APPLICATION_SPECIFIC_16, "VM_MEMORY_APPLICATION_SPECIFIC_16"},
    {256, "VM_MEMORY_COUNT"}
};

static std::set<unsigned int> g_malloc_user_tags = {
    VM_MEMORY_MALLOC,           // 1
    VM_MEMORY_MALLOC_TINY,      // 7
    VM_MEMORY_MALLOC_SMALL,     // 2
    VM_MEMORY_MALLOC_MEDIUM,
    VM_MEMORY_MALLOC_LARGE,
    VM_MEMORY_MALLOC_HUGE,
    VM_MEMORY_MALLOC_NANO,
//    VM_MEMORY_REALLOC,
//    VM_MEMORY_MALLOC_LARGE_REUSED
};


// from vm_statistics.h
const char * vm_region_usertag_name(unsigned int user_tag){
    map<int, string>::iterator iter = vm_region_names.find(user_tag);
    if(iter != vm_region_names.end()){
        return iter->second.c_str();
    }else{
        return "null";
    }
}

// from vm_statistics.h
bool vm_region_is_malloc_usertag(unsigned int user_tag) {
    return g_malloc_user_tags.find(user_tag) != g_malloc_user_tags.end();
}

